# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggoutbreak)

# unit test start: seq.time_period ----

test_that("seq.time_period unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = seq.time_period
  

  x <- as.time_period(as.Date("2025-01-01") + 0:2, anchor = "start", unit = "1 day")
  y <- as.time_period(as.Date("2025-01-07") + 0:2, anchor = "start", unit = "1 day")
  testthat::expect_equal(as.numeric(c(x, y)), c(0, 1, 2, 6, 7, 8))
  testthat::expect_equal(as.numeric(c(y, x)), c(0, 1, 2, -6, -5, -4))
  
  z <- as.time_period(as.Date("2025-01-01") + 0:2 * 7, anchor = "start", unit = "1 week")
  testthat::expect_equal(as.numeric(c(x, z)), c(0, 1, 2, 0, 7, 14))
  testthat::expect_equal(
    as.numeric(c(z, x)),
    c(0, 1, 2, 0, 0.142857142857143, 0.285714285714286)
  )
  
  testthat::expect_equal(
    as.Date(c(y, z)),
    structure(c(20095, 20096, 20097, 20089, 20096, 20103), class = "Date")
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/periodic-times.R"), c(918, 1, 918+1, 1))
  )
})

# unit test end: seq.time_period ----
# unit test start: as.time_period ----

test_that("as.time_period unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = as.time_period
  

  tmp <- as.time_period(grates::as_epiweek("2019-W12", format = "yearweek") + 0:2)
  testthat::expect_equal(
    lubridate::epiweek(as.Date(tmp)),
    c(12, 13, 14)
  )
  
  tmp <- as.time_period(grates::as_isoweek("2019-W12", format = "yearweek") + 0:2)
  testthat::expect_equal(
    lubridate::isoweek(as.Date(tmp)),
    c(12, 13, 14)
  )
  
  x <- as.time_period(as.Date("2025-01-01") + 0:2, anchor = "start", unit = "1 day")
  y <- as.time_period(as.Date("2025-01-07") + 0:2, anchor = "start", unit = "1 day")
  testthat::expect_equal(as.numeric(c(x, y)), c(0, 1, 2, 6, 7, 8))
  testthat::expect_equal(as.numeric(c(y, x)), c(0, 1, 2, -6, -5, -4))
  
  z <- as.time_period(as.Date("2025-01-01") + 0:2 * 7, anchor = "start", unit = "1 week")
  testthat::expect_equal(as.numeric(c(x, z)), c(0, 1, 2, 0, 7, 14))
  testthat::expect_equal(
    as.numeric(c(z, x)),
    c(0, 1, 2, 0, 0.142857142857143, 0.285714285714286)
  )
  
  testthat::expect_equal(
    as.Date(c(y, z)),
    structure(c(20095, 20096, 20097, 20089, 20096, 20103), class = "Date")
  )
  
  seq(x[[1]], y[[1]])

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/periodic-times.R"), c(880, 1, 880+1, 1))
  )
})

# unit test end: as.time_period ----
# unit test start: S3_time_period ----

test_that("S3_time_period unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  

  default <- new_time_period(as.numeric(1:10))
  shifted <- new_time_period(as.numeric(1:10), start_date = as.Date("1970-01-10"))
  stretched <- new_time_period(as.numeric(1:10), unit = lubridate::weeks(1))
  
  testthat::expect_equal(
    format(default),
    c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
  )
  
  testthat::expect_equal(
    vec_ptype_full(default),
    "time unit: day, origin: 1970-01-01 (a Thursday)"
  )
  
  testthat::expect_equal(
    vec_ptype_full(shifted),
    "time unit: day, origin: 1970-01-10 (a Saturday)"
  )
  
  testthat::expect_equal(
    vec_ptype_full(stretched),
    "time unit: week, origin: 1970-01-01 (a Thursday)"
  )
  
  testthat::expect_equal(vec_ptype_abbr(default), "t[day]")
  
  dshifted <- vec_cast(default, shifted)
  testthat::expect_equal(
    as.Date(dshifted) == as.Date(default),
    c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)
  )
  
  dsquashed <- vec_cast(default, stretched)
  testthat::expect_equal(
    vec_cast(dsquashed, double()),
    c(
      0.142857142857143,
      0.285714285714286,
      0.428571428571429,
      0.571428571428571,
      0.714285714285714,
      0.857142857142857,
      1,
      1.14285714285714,
      1.28571428571429,
      1.42857142857143
    )
  )
  
  testthat::expect_equal(
    diff(vec_cast(stretched, Sys.Date())),
    structure(
      c(7, 7, 7, 7, 7, 7, 7, 7, 7),
      class = "difftime",
      units = "days"
    )
  )
  
  # Cast numeric to time period check equality
  testthat::expect_equal(
    all(c(shifted, vec_cast(11:20, shifted)) == 1:20),
    TRUE
  )
  
  # Different cadence can be matched:
  testthat::expect_equal(
    vec_match(default, stretched),
    c(NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA)
  )
  
  # Matching is within tolerance
  testthat::expect_equal(all(default == default + 0.0000001), TRUE)
  
  # comparison
  testthat::expect_equal(
    shifted > rev(shifted),
    c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE)
  )
  
  # sorting
  testthat::expect_equal(
    as.numeric(sort(sample(shifted, 10))),
    c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
  )
  
  # Arithmetic:
  tmp <- withr::with_seed(100, default + runif(10))
  testthat::expect_equal(any(tmp == default), FALSE)
  testthat::expect_equal(all(floor(tmp) == default), TRUE)
  
  # Basic operation returns the time_period
  testthat::expect_equal(is.time_period(default - 1), TRUE)
  
  # modulo works:
  testthat::expect_equal(default %% 3, c(1, 2, 0, 1, 2, 0, 1, 2, 0, 1))
  # Other operations will work but the result has to be interpreted relative to origin
  testthat::expect_equal(sin(default * pi / 2), c(
    1,
    0,
    -1,
    0,
    1,
    0,
    -1,
    0,
    1,
    0
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/periodic-times.R"), c(21, 1, 21+1, 1))
  )
})

# unit test end: S3_time_period ----
# unit test start: .day_interval ----

test_that(".day_interval unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .day_interval
  

  r <- c(1, rpois(10, 3) + 1)
  interval <- 2
  dates <- as.Date("2025-01-01") + r * interval
  testthat::expect_equal(.day_interval(dates) == interval, TRUE)
  
  interval <- 0.5
  dates <- as.Date("2025-01-01") + r * interval
  testthat::expect_equal(.day_interval(dates) == interval, TRUE)

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/periodic-times.R"), c(634, 1, 634+1, 1))
  )
})

# unit test end: .day_interval ----
# end of unit tests ----
