# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggoutbreak)

# unit test start: .infer_grouping ----

test_that(".infer_grouping unit test", {
  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .infer_grouping

  df <- dplyr::tibble(
    original_grp = as.vector(sapply(LETTERS[1:4], rep, 20)),
    to_find = as.vector(sapply(letters[1:10], rep, 8)),
    to_make_unique = rep(1:10, 8),
    distractor = runif(80)
  ) %>%
    dplyr::group_by(original_grp)
  unique_col <- as.symbol("to_make_unique")
  tmp <- .infer_grouping(df, to_make_unique)
  testthat::expect_equal(
    format(dplyr::groups(tmp)),
    c("original_grp", "to_find")
  )

  # generates a failure if the overall test is failing with a link to the
  # source of the unit test:
  testthat::expect(
    rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/utils-data.R"), c(249, 1, 249 + 1, 1))
  )
})

# unit test end: .infer_grouping ----
# end of unit tests ----
