# Generated by doctest: do not edit by hand
# Please edit file in R/import-standalone-singleton.R

test_that("Doctest: .singleton", {
  # Created from @doctest for `.singleton`
  # Source file: R/import-standalone-singleton.R
  # Source line: 30
  fixed_rnorm = .singleton(rnorm(10))
  a = fixed_rnorm()
  expect_equal(b = fixed_rnorm(), a)
})

